name: Maven Release Package Build

on:
  push:
    branches:
      - 'master'
    tags:
      - 'release*'
jobs:
  build-test-publish:
    name: Build Test Publish
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Print Version
        id: compute_version
        run: |
          chmod +x myBash.sh
          version=$(./myBash.sh)
          echo $version
          echo "##[set-output name=version;]$(echo $version)"

      - name: Github reference
        run: |
          ver=${{ github.event.ref }}
          echo $ver

      - name: Reference
        run: |
          ver=$(git rev-parse --abbrev-ref HEAD)
          echo $ver

      - name: github object
        run: |
          ver=${{ toJSON(github) }}
          echo $ver

      - name: Gradle Build
        run: gradle build
          
      - name: Unit Test
        run: gradle test

      - name: Gradle Publish
        run: gradle -Pgpr.user=nachiappannk -Pgpr.key=${{ secrets.GITHUB_TOKEN }} -Pgpr.version=${{ steps.compute_version.outputs.version }} publish
