name: Extra Build

on:
  repository_dispatch:

  push:
    branches:
      - 'master'
      - 'release*'

jobs:

  build-and-test:
    name: Extra Build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
          
      - name: Making Custom Scripts As Executable
        run: |
          cd .github/scripts
          echo "::set-env name=PATH::${PATH}:$(pwd)"
          chmod +x *
    
      - name: If Repository Dispatch Checkout Sha
        if: github.event_name == 'repository_dispatch'
        run: git checkout "${{  github.event.client_payload.buildSha }}"
        
      - name: Setting the build sha variable
        run: echo "::set-env name=CI_BUILD_SHA::$(git log  -n 1 --format=format:%H)"      



        
      - name: logging
        run: |
          echo "CI_BUILD_SHA is ${CI_BUILD_SHA}"
          
        
      - name: BuildType
        run: echo "${{  github.event.client_payload.buildType }}"

      - name: BuildBranch
        run: echo "${{  github.event.client_payload.buildBranch }}"        

      - name: BuildSha
        run: echo "${{  github.event.client_payload.buildSha }}"
        
      - name: Show PATH 1
        run: echo "${PATH}"

      - name: Set Path
        run: export PATH=${PATH}:/bin/nash
        
      - name: Show PATH 2
        run: echo "${PATH}"
        
      - name: Show bash rc
        run: cat ~/.bashrc

      - name: Show bash rc
        run: echo "export PATH=${PATH}:bin/nash" >> ~/.bashrc

      - name: Show PATH 3
        run: echo "${PATH}"
                
        
        

