name: Extra Build

on:
  repository_dispatch:

jobs:

  build-and-test:
    name: Extra Build
    runs-on: ubuntu-18.04

    steps:
      - name: BuildType
        run: echo "${{  github.event.client_payload.buildType }}"

      - name: BuildBranch
        run: echo "${{  github.event.client_payload.buildBranch }}"        

      - name: BuildSha
        run: echo "${{  github.event.client_payload.buildSha }}"
        
      - name: Show PATH 1
        run: echo "${PATH}"

      - name: Set Path
        run: export PATH=${PATH}:/bin/nash
        
      - name: Show PATH 2
        run: echo "${PATH}"

