name: Extra Build

on:
  repository_dispatch:

jobs:

  build-and-test:
    name: Extra Build
    runs-on: ubuntu-18.04

    steps:
      - name: Logging
        run: echo "hi how are you doing?"

      - name: accessing payload
        run: echo "${{  github.event.client_payload.sha }}"        
