name: Master Build


on:
  push:
    branches:
      - 'master'
      - 'rel-*'

jobs: 
  master-build:
    name: Master Build
    runs-on: ubuntu-18.04

    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/checkout@v1
    
      - name: Get Release Version
        id: compute-release-version
        uses: ZeroWasteTeam/action-compute-version@convertion
        with:
          current-branch:  ${{ github.ref##*/ }}
          
      - name: Gradle Build
        run: gradle build
          
      - name: Unit Test
        run: gradle test

      - name: Gradle Publish
        run: gradle -Pgpr.repo="https://maven.pkg.github.com/ZeroWasteTeam/SampleJavaMavenPackage" -Pgpr.user="${{ github.actor }}" -Pgpr.key="${{ secrets.GITHUB_TOKEN }}" -Pgpr.version="${{ steps.compute-release-version.outputs.version}}" publish
