name: Master Build


on:
  push:
    branches:
      - 'master'
      - 'rel-*' # This is not needed for maven package build. This is needed for docker builds (release flow)

jobs: 
  master-build:
    name: Master Build
    runs-on: ubuntu-18.04

    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/checkout@v1
    
      - name: Get Release Version
        id: compute-release-version
        uses: ZeroWasteTeam/actions/compute-version@master
        with:
          build-branch:  ${{ github.ref }}
          is-release-flow: false # This line is not needed for docker build. For docker build the value has to be true (which is the default) value

      - name: Gradle Build
        run: gradle build
          
      - name: Unit Test
        run: gradle test

 #     - name: Gradle Publish
 #       run: gradle -Pgpr.repo="https://maven.pkg.github.com/ZeroWasteTeam/SampleJavaMavenPackage" -Pgpr.user="${{ github.actor }}" -Pgpr.key="${{ secrets.GITHUB_TOKEN }}" -Pgpr.version="${{ steps.compute-release-version.outputs.version}}" publish
        
      - name: Publish Script
        run: |
          chmod +x ./scripts-*.sh
          ./scripts-publish.sh ${{ github.actor }} ${{ secrets.GITHUB_TOKEN }} ${{ steps.compute-release-version.outputs.version}}



