name: Merge To Master Build

on:
  push:
    branches:
      - 'master'
    tags:
      - 'test*'

jobs:
  test:
    name: Test TAG
    runs-on: ubuntu-18.04

    steps:
      - name: Unit Test
        run: echo "HELLO"

      - run: echo ${{github.ref}}
        name: Print Ref
 