name: Merge To Master Build

on:
  push:
    branches:
      - 'master'
    tags:
      - 'test*'

jobs:
  test:
    name: Test TAG
    runs-on: ubuntu-18.04

    steps:
      - name: Unit Test
        if: github.ref == 'refs/heads/master'
        run: echo "It's the master branch"

      - run: echo ${{github.ref}}
        name: Print Ref
        if: startsWith(github.ref, 'refs/tags/test')
 
