name: Maven Package Release Build

on:
  push:
    branches:
      - 'master'
      - 'release*'
    tags:
      - 'release*'
jobs:
  build-test-publish:
    name: Build Test Publish
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Compute Version
        id: compute_version
        run: |
          chmod +x version-generator.sh
          version=$(./version-generator.sh)
          echo $version
          echo "##[set-output name=version;]$(echo $version)"
          
      - name: Branch Name
        run: echo "${GITHUB_REF#refs/heads/}"
      
      - name: Tag Name
        run: echo "${GITHUB_REF#refs/tags/}"
      
      - name: All Branches
        run: echo $(git branch -r --contains ${GITHUB_SHA})
      
      
      - name: Gradle Build
        run: gradle build
          
      - name: Unit Test
        run: gradle test

      - name: Gradle Publish
        run: gradle -Pgpr.user=nachiappannk -Pgpr.key=${{ secrets.GITHUB_TOKEN }} -Pgpr.version=${{ steps.compute_version.outputs.version }} publish
