name: New Build

on:
  repository_dispatch:

  push:
    branches:
      - 'master'
      - 'release*'

jobs:

  build-test-version-publish:
    name: New Build
    runs-on: ubuntu-18.04

    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/checkout@v2
    
      - uses: ZeroWasteTeam/action-prepare-workspace@master
        id: prepare-ws

      - name: Get Release Version
        id: compute-release-version
        uses: ZeroWasteTeam/action-compute-version@convertion
        with:
          current-branch: ${{steps.prepare-ws.outputs.build-branch }}

      - name: Gradle Build
        run: gradle build
          
      - name: Unit Test
        run: gradle test

      - name: Gradle Publish
        run: gradle -Pgpr.repo="https://maven.pkg.github.com/ZeroWasteTeam/SampleJavaMavenPackage" -Pgpr.user="${{ github.actor }}" -Pgpr.key="${{ secrets.GITHUB_TOKEN }}" -Pgpr.version="${{ steps.compute-release-version.outputs.version}}" publish
