name: Maven Package Release Build

on:
  repository_dispatch:

  push:
    branches:
      - 'master'
      - 'release*'

jobs:

  build-test-version-publish:
    name: New Build
    runs-on: ubuntu-18.04

    steps:

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/checkout@v1
    
      - name: If Repository Dispatch Checkout Sha
        if: github.event_name == 'repository_dispatch'
        run: git checkout -f "${{  github.event.client_payload.buildSha }}"
        
      - name:  Set build branch
        run: |
          set -e
          if [[ ${{ github.event_name }} = 'repository_dispatch' ]] ;
          then
            BUILD_BRANCH="${{  github.event.client_payload.buildBranch }}"            
          else
            BUILD_BRANCH="${GITHUB_REF#refs/heads/}"
          fi
          echo "::set-env name=CI_BUILD_BRANCH::${BUILD_BRANCH}"

      - name: Get Release Version
        id: compute-release-version
        uses: ZeroWasteTeam/action-read-base-version@convertion
        with:
          current-branch: "${BUILD_BRANCH}"
          
      - name: Gradle Build
        run: gradle build
          
      - name: Unit Test
        run: gradle test

      - name: Gradle Publish
        run: gradle -Pgpr.repo="https://maven.pkg.github.com/ZeroWasteTeam/SampleJavaMavenPackage" -Pgpr.user="${{ github.actor }}" -Pgpr.key="${{ secrets.GITHUB_TOKEN }}" -Pgpr.version="${{ steps.compute-release-version.outputs.version}}" publish
