name: Pull Request Build

on:
  pull_request:
    branches:
      - 'master'
jobs:

  build-and-test:
    name: PR - Build and Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Git hub ref
        run: echo $GITHUB_REF
        
      - name: Git hub sha
        run: echo $GITHUB_SHA

      - name: Git Modified Files
        run: |
          echo "Checking Version File is Modified"
          number-of-files-modifies=$(git diff --name-only "origin/master..$GITHUB_SHA" | wc -l)
          echo $(number-of-files-modifies)
          is-version-file-modified=[[ $(git diff --name-only "origin/master..$GITHUB_SHA" | grep version.txt | wc -l) == 1 ]]
          echo $is-version-file-modified
        
      - name: PR - Gradle Build
        run: gradle build
        
      - name: PR - Gradle Test
        run: gradle test
      
