name: Pull Request Build

on:
  pull_request:
    branches:
      - 'master'
      - 'release-*'
jobs:

  build-and-test:
    name: PR - Build and Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Printing PATH
        run: echo "PATH is ${PATH}"
          
      - name: Making Custom Scripts As Executable
        run: |
          cd .github/scripts
          echo "PATH is ${PATH}"
          NEW_PATH="${PATH}:$(pwd)"
          echo "NEW_PATH is ${NEW_PATH}"
          echo "::set-env name=PATH::${NEW_PATH}"
          chmod +x *

      - name: For Non Master Branch make sure version file is not modified
        run: ci-assertVersionIsModified "origin/${{ github.base_ref }}" "${GITHUB_SHA}"

      - name: Github Sha
        run: echo $GITHUB_SHA

      - name: Github ref
        run: echo $GITHUB_REF
        
      - name: Head ref
        run: echo ${{ github.head_ref }}
        
      - name: Base ref
        run: echo ${{ github.base_ref }}
        
      - name: myStuff:txt
        run: git show "${GITHUB_SHA}:myStuff.txt"
        
        
      - name: myStuff:txt
        run: git show "origin/${{ github.base_ref }}:myStuff.txt"

      #If master branch and if version file is modified. Make sure nothing is modified
      
      #if release branch make sure not version file is not modified
      
      #If master and version file  is modified make sure the version is correctly changed
      
      
      - name: PR - Gradle Build
        run: gradle build
        
      - name: PR - Gradle Test
        run: gradle test
      
