name: Maven Package Release Build

on:
  repository_dispatch:
  push:
    branches:
      - 'master'
      - 'release*'

jobs:

  build-test-version-publish:
    name: Build Test Version Publish
    runs-on: ubuntu-18.04

    steps:
      - uses: ZeroWasteTeam/action-read-base-version@master
